_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 51
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 51
                - 53
                - 55
                - 103
            "3":
                - 7
                - 13
                - 16
                - 23
                - 55
                - 66
            "4": 3.12.3
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
scenario_id:
    value: 5
task_id:
    value: 1
