from models.simclr import SimCLR
from models.mocov2 import MoCov2
from models.mocov2plus import MoCov2Plus
from models.byol import BYOL
from models.barlow_twins import BarlowTwins
from models.swav import SwAV
from models.simsiam import SimSiam
from models.vicreg import VICReg
from models.linear_classifier import Classifier