model_name: "BarlowTwins"
split_strategy: "class"
dataset: "cifar100"
image_dim: 32

num_classes: 100
num_tasks: 5
seeds: [5]

feature_dim: 512
projection_hidden_dim: 2048
projection_output_dim: 2048

scale_loss: 0.1
lambda_param: 5.0e-3

trust_coefficient: 0.02
clip_lr: True

momentum: 0.9
train_batch_size: 256
train_accumulate_grad_batches: 1
train_epochs: 500

test_batch_size: 128
test_accumulate_grad_batches: 1
test_epochs: 100

optimizer:
  name: "lars"
  train_learning_rate: 0.3
  classifier_learning_rate: 0.004
  weight_decay: 1.0e-4

num_workers: 8
set_float32_matmul_precision: "high"

# Augmentations
gaussian_blur: [0.0, 0.0]
solarization: [0.0, 0.2]
brightness: 0.4
contrast: 0.4
saturation: 0.2
hue: 0.1

# overwrite Pytorch Lightening default
num_devices: 1
gpu_devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "auto"
precision: 16-mixed

# Classifier parameters
knn_neighbours: 200
knn_temperature: 0.1

# Hard defaults
reference_batch_size: 256