model_name: "BYOL"

dataset: "cifar100"
image_dim: 32

num_classes: 100
num_tasks: 5
seeds: [5]

feature_dim: 512
projection_hidden_dim: 4096
projection_output_dim: 256
prediction_hidden_dim: 4096

momentum_encoder:
  base_tau: 0.99
  final_tau: 1.0

momentum: 0.9
train_batch_size: 256
train_accumulate_grad_batches: 1
train_epochs: 500

trust_coefficient: 0.02
clip_lr: True

test_batch_size: 256
test_accumulate_grad_batches: 1
test_epochs: 100

optimizer:
  name: "lars"
  train_learning_rate: 1.0
  classifier_learning_rate: 0.1
  weight_decay: 1.0e-5

num_workers: 8
set_float32_matmul_precision: "high"

# overwrite Pytorch Lightening default
num_devices: 1
gpu_devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "auto"
precision: 16-mixed

# Hard defaults
reference_batch_size: 256