model_name: "MoCov2Plus"
split_strategy: "class"
dataset: "cifar100"
image_dim: 32

num_classes: 100
num_tasks: 5
seeds: [5]

feature_dim: 512
hidden_dim: 2048
output_dim: 256

loss:
  queue_size: 65536
  temperature: 0.2

momentum_encoder:
  base_tau: 0.99
  final_tau: 0.999
  
train_batch_size: 256
train_accumulate_grad_batches: 1
train_epochs: 500

test_batch_size: 128
test_accumulate_grad_batches: 1
test_epochs: 100

optimizer:
  name: "lars"
  train_learning_rate: 0.4
  classifier_learning_rate: 0.04
  weight_decay: 1.0e-4
  momentum: 0.9
  trust_coefficient: 0.02
  clip_lr: True

num_workers: 8
set_float32_matmul_precision: "high"

# Augmentations
gaussian_blur: [0.5, 0.0]
solarization: [0.0, 0.0]
brightness: 0.8
contrast: 0.8
saturation: 0.8
hue: 0.2

# Classifier parameters
knn_neighbours: 200
knn_temperature: 0.1

# overwrite Pytorch Lightening default
num_devices: 1
gpu_devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "auto"
precision: 16-mixed

# Hard defaults
reference_batch_size: 256