model_name: "VICReg"
split_strategy: "class"
dataset: "cifar100"
image_dim: 32

num_classes: 100
num_tasks: 5
seeds: [5]

feature_dim: 512
projection_hidden_dim: 2048
projection_output_dim: 2048
projection_layers: 2

sim_loss_weight: 25.0
var_loss_weight: 25.0
cov_loss_weight: 1.0
epsilon: 0.2

trust_coefficient: 0.02
clip_lr: True

gather_distributed: False

momentum: 0.9
train_batch_size: 256
train_accumulate_grad_batches: 1
train_epochs: 500

test_batch_size: 128
test_accumulate_grad_batches: 1
test_epochs: 100

optimizer:
  name: "lars"
  train_learning_rate: 0.1
  classifier_learning_rate: 0.04
  weight_decay: 1.0e-4

num_workers: 4
set_float32_matmul_precision: "high"

# Augmentations
gaussian_blur: [0.0, 0.0]
solarization: [0.1, 0.1]
brightness: 0.4
contrast: 0.4
saturation: 0.2
hue: 0.1

# Classifier parameters
knn_neighbours: 200
knn_temperature: 0.1

# overwrite Pytorch Lightening default
num_devices: 1
gpu_devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "auto"
precision: 16-mixed

# Hard defaults
reference_batch_size: 256