model_name: "VICReg"

dataset: "cifar100"
image_dim: 32

num_classes: 100
num_tasks: 1
seeds: [5]

feature_dim: 512
projection_hidden_dim: 2048
projection_output_dim: 2048
projection_layers: 2

sim_loss_weight: 25.0
var_loss_weight: 25.0
cov_loss_weight: 1.0
epsilon: 0.2

trust_coefficient: 0.02
clip_lr: True

gather_distributed: False

momentum: 0.9
train_batch_size: 256
train_accumulate_grad_batches: 1
train_epochs: 500

test_batch_size: 256
test_accumulate_grad_batches: 1
test_epochs: 100

optimizer:
  name: "lars"
  train_learning_rate: 0.3
  classifier_learning_rate: 0.1
  weight_decay: 1.0e-4

num_workers: 4
set_float32_matmul_precision: "high"

# overwrite Pytorch Lightening default
num_devices: 1
gpu_devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "auto"
precision: 16-mixed

# Hard defaults
reference_batch_size: 256