model_name: "MoCov2Plus"
version: "v2"

dataset: "cifar100"
image_dim: 32

num_classes: 100
num_tasks: 5
class_increment: 20
seeds: [5]

feature_dim: 512
hidden_dim: 2048
output_dim: 128

queue_size: 32768
temperature: 0.2

train_learning_rate: 0.4
weight_decay: 1.0e-4
momentum: 0.9
train_batch_size: 256
train_accumulate_grad_batches: 1
train_epochs: 500
accelerator: "gpu"
num_devices: 1
gpu_devices: [0]

test_batch_size: 256
test_accumulate_grad_batches: 1
test_epochs: 100
classifier_learning_rate: 0.3

num_workers: 4
set_float32_matmul_precision: "high"