model_name: "MoCov2Plus"

dataset: "cifar100"
image_dim: 32

num_classes: 100
num_tasks: 1
seeds: [5]

feature_dim: 512
hidden_dim: 2048
output_dim: 256

trust_coefficient: 0.02
clip_lr: True

queue_size: 65536
temperature: 0.2

momentum_encoder:
  base_tau: 0.99
  final_tau: 0.999
  
momentum: 0.9
train_batch_size: 256
train_accumulate_grad_batches: 1
train_epochs: 500

test_batch_size: 256
test_accumulate_grad_batches: 1
test_epochs: 100

optimizer:
  name: "lars"
  train_learning_rate: 0.4
  classifier_learning_rate: 0.3
  weight_decay: 1.0e-4

num_workers: 4
set_float32_matmul_precision: "high"

# overwrite Pytorch Lightening default
num_devices: 1
gpu_devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "auto"
precision: 16-mixed

# Hard defaults
reference_batch_size: 256