model_name: "MoCov2"
version: "v2"

dataset: "cifar100"
image_dim: 32

num_tasks: 1
num_classes: 100
class_increment: 100
seeds: [5]

feature_dim: 512
hidden_dim: 2048
output_dim: 256

queue_size: 65536
temperature: 0.2

train_learning_rate: 0.3
weight_decay: 1.0e-4
momentum: 0.9
train_batch_size: 256
train_accumulate_grad_batches: 1
train_epochs: 1000

test_batch_size: 256
test_accumulate_grad_batches: 1
test_epochs: 100
classifier_learning_rate: 0.3

num_workers: 4
set_float32_matmul_precision: "high"

# overwrite Pytorch Lightening default
num_devices: 1
gpu_devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "auto"
precision: 16-mixed