model_name: "SimCLR"
dataset: "cifar100"

num_classes: 100
num_scenario: 3

feature_dim: 512
train_learning_rate: 0.075
weight_decay: 1.0e-06
momentum: 0.9
train_batch_size: 128
train_accumulate_grad_batches: 2
train_epochs: 10
device: "gpu"
num_devices: 1
gpu_devices: [0]

num_workers: 8

test_batch_size: 256
test_accumulate_grad_batches: 1
test_epochs: 10
test_learning_rate: 0.1