model_name: "SimCLR"
dataset: "cifar100"

image_dim: 32

num_classes: 100
seeds: [24, 42, 1992]

feature_dim: 512
hidden_dim: 2048
output_dim: 128

train_learning_rate: 0.04
weight_decay: 1.0e-4
momentum: 0.9
train_batch_size: 256
train_accumulate_grad_batches: 1
train_epochs: 500
device: "gpu"
num_devices: 2
gpu_devices: [0, 1]

num_workers: 16

test_batch_size: 256
test_accumulate_grad_batches: 1
test_epochs: 100
test_learning_rate: 0.1